### ISSUE TITLE
Godot 4

### ISSUE THREAD

**Issue by mattkanwisher** [croconut/godot-tester#26]
Any interest in porting this to Godot 4?

**Comment by RGonzalezTech** [comment]
I haven't upgraded my project to Godot 4.0, but if I ever do I'll open a PR with any changes I make to this action. Hopefully someone else beats me to it 😅 

If you need to support 4.0 and GUT 9 right now, you'd just need to make sure that:

1. `entrypoint.sh` script downloads Godot 4 properly
2. upgrade the GUT addon to v9 or otherwise make sure it's using GUT 9
3. use the right CLI commands for GUT. You can see the CLI available for GUT 9 here: https://bitwes.github.io/GutWiki/Godot4/Command-Line.html

I recently had a PR get merged in which bumped this action to 3.0, but I don't know if there are any plans for the original developer to continue developing it or if they're only in "PR-Review" mode.

It would be nice to continue using this action when it comes time to upgrade to Godot 4 though 😁

**Comment by RGonzalezTech** [comment]
Update: Looks like someone forked the action and I _think_ it supports Godot 4? I haven't tested it, though.

https://github.com/ghgsrt/godot-tester-ci

Hope that helps anyone who runs into this thread 😅

**Comment by croconut** [comment]
Thanks @RGonzalezTech, looks like that would be a good action to swap to. I haven't really had time to look into this project for a while and I don't use Godot anymore either, so I probably won't end up doing much work on this. 

If anyone wants to take on the project I can either archive or pass over the repo.

**Comment by RGonzalezTech** [comment]
Thanks for responding @croconut :)

If I get a chance to port it to Godot 4, I will humbly accept the torch. If someone else beats me to it, that's cool too hahaha.

**Comment by RGonzalezTech** [comment]
Following up on this. I believe I have a working solution on my fork.

It includes a refactoring and backwards compatibility with v3.x. See my branch here: https://github.com/RGonzalezTech/godot-tester/tree/rg/support-godot-4

@croconut - If I opened a pull request, would you review & merge it in, or should I just merge it into my `master` branch and maintain it on my own fork going forward?

Let me know ✌

**Comment by croconut** [comment]
@RGonzalezTech I can add you as collaborator. Not sure if transferring the repo would cause issues for anyone using it, but we can do that if you delete your copy of it. Or you can publish your fork on your account to the actions page and I can archive this repo. Up to you

**Comment by croconut** [comment]
Next time I do something like this I need to start with an organization first @.@

**Comment by RGonzalezTech** [comment]
Hahaha, I'm down to just contribute to this repository. it's already published and versioned 👍

**Comment by croconut** [comment]
@RGonzalezTech Sounds good. I've set the master branch to require PRs before merging and squash commits only for consistency.

Let's get your branch in so I can convert the entry point to python, unless you'd like to do it or would prefer a different language. 

If I'm going to do PR reviews, I'm ditching bash for a nicer language. I'm fine with js/typescript/python/rust. Tbh, most of the reason I didn't want to update this is that I just dislike bash.

**Comment by RGonzalezTech** [comment]
I've been enjoying JS/Node lately, but I don't mind Python :)

Lol, hope my bash is easy to read & follow, it's not my favorite language either 😵 

See PR #27

**Comment by croconut** [comment]
Closing with merge of #27
